#!/bin/bash

# Pulls the IP address from line 5 of the "config" file and assigns it to the "oip" variable
oip=$(sed -n '5s/.*= //p' config)

# Pulls the internal IP address and assigns it to the "nip" variable
nip=$(ifconfig | awk '/inet /{print $2}' | grep -v '127.0.0.1')

# Replaces the old IP address with the new/current IP address in the "config" file
sed -i "s/${oip}/${nip}/g" config

# Removes any residual "sed" files from previous variable substitutions
rm -f ~/Smartphone-Pentest-Framework/frameworkconsole/sed*

# Changes the directory to "~/Smartphone-Pentest-Framework/frameworkconsole/" and executes the "framework.py" script
cd ~/Smartphone-Pentest-Framework/frameworkconsole && ./framework.py
